### ISSUE TITLE
Error message during update from 0.0.70 to 0.0.71

### ISSUE THREAD

**Issue by Karatzie** [fl4p/batmon-ha#152] opened 2023-10-11 17:52 UTC
Hi Fabian.

I got this error message during update from 0.0.70 to 0.0.71.

**The command '/bin/ash -o pipefail -c pip3 install -r requirements.txt' returned a non-zero code: 1**

The update is not performed.

BR
Andreas

**Comment by fl4p** [comment] 2023-10-17 18:26
duplicate of https://github.com/fl4p/batmon-ha/issues/147

**Closed by fl4p** 2023-10-17 18:26 UTC

**Comment by Karatzie** [comment] 2023-10-17 19:14
I use the RP3 and Home Assistant OS 10.5 64 bit.
